name: push test 1

on: 
  push:
    branches:
      - feature/*
      
jobs: 
  name: merging feature branch to main 
  runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
