name: push test 2

on: 
  push:
    branches:
      - feature/*
jobs: 
  RunPullRequestTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      
